[phases.setup]
nixPkgs = ["maven"]

[phases.install]
cmds = ["mvn clean package -DskipTests"]

[phases.build]
cmds = ["echo 'Build completed'"]

[start]
cmd = "java -jar target/pet_store-0.0.1-SNAPSHOT.jar"
