# ================================================
# CONFIGURACIÓN DE RAILWAY - DOCKER BUILD
# ================================================

[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"

[deploy]
startCommand = "java -Xmx512m -Xms256m -Djava.security.egd=file:/dev/./urandom -jar /app/app.jar"
healthcheckPath = "/actuator/health"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

# Variables de entorno
[env]
SPRING_PROFILES_ACTIVE = "railway"
