[build]
builder = "nixpacks"

[deploy]
startCommand = "java -jar target/pet_store-0.0.1-SNAPSHOT.jar"
healthcheckPath = "/actuator/health"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[env]
SPRING_PROFILES_ACTIVE = "prod"
